//! Build script: runs tauri-build with an explicit app ACL so that only the setup window can
//! call app commands, and, for Windows (MSVC), embeds the application manifest into every
//! linked target.
//!
//! Every `#[tauri::command]` function in `src/commands.rs` (or `src/commands/*.rs`) gets the
//! `allow-<name>` permission Tauri generates, and this script bundles all of them into one
//! permission set, `app-commands`, which `capabilities/setup.json` grants to the window
//! labelled "setup" and to nothing else.
//!
//! Why: once an app manifest exists, Tauri checks every app command against the capabilities,
//! so a window in no capability (the Crawler AI window, which loads http://localhost:3000)
//! cannot call any of them — even if a future Tauri treated it as a local origin. Deriving the
//! list from the source keeps it from drifting: a new command works from the setup window
//! without editing a second file. A command defined anywhere else is denied at runtime (in dev
//! builds the rejection names the missing permission).
//!
//! The Windows manifest is linked here rather than through tauri-build's resource because
//! tauri-build only attaches it to the app binary, and test binaries without it die with
//! STATUS_ENTRYPOINT_NOT_FOUND (the same workaround Tauri's own build script uses).
//! windows-app-manifest.xml is a byte-for-byte copy of tauri-build's default (a Common
//! Controls v6 dependency).

use std::{
    fs,
    path::{Path, PathBuf},
};

const SET_FILE: &str = "permissions/autogenerated/app-commands.toml";

fn main() {
    println!("cargo:rerun-if-changed=src/commands.rs");
    println!("cargo:rerun-if-changed=src/commands");

    // tauri-build copies the bundle resources next to dev binaries and fails when `../stack`
    // is missing. `tauri build` and `tauri dev` stage it first (scripts/stage-stack.mjs); a
    // plain `cargo check` / `cargo test` on a fresh clone gets an empty directory instead.
    // A release build must never ship without the stack, so there it is an error.
    println!("cargo:rerun-if-changed=../stack/VERSION");
    let stack = Path::new("../stack");
    if !stack.join("VERSION").is_file() {
        if std::env::var("PROFILE").as_deref() == Ok("release") {
            panic!("desktop/stack is not staged: run `npm run stage-stack` (tauri build does it in beforeBuildCommand)");
        }
        fs::create_dir_all(stack).expect("create ../stack");
        println!("cargo:warning=desktop/stack is not staged (empty); `npm run stage-stack` fills it, and tauri build/dev run it");
    }

    let names = command_names();
    write_if_changed(Path::new(SET_FILE), &command_set_toml(&names));

    // AppManifest wants &'static; a build script runs once, so leaking is fine.
    let names: &'static [&'static str] = Box::leak(
        names
            .into_iter()
            .map(|n| &*Box::leak(n.into_boxed_str()))
            .collect::<Vec<&'static str>>()
            .into_boxed_slice(),
    );
    let mut attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(names));

    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if target_os == "windows" && target_env == "msvc" {
        let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets it"))
            .join("windows-app-manifest.xml");
        println!("cargo:rerun-if-changed={}", manifest.display());
        println!("cargo:rustc-link-arg=/MANIFEST:EMBED");
        println!("cargo:rustc-link-arg=/MANIFESTINPUT:{}", manifest.display());
        attributes = attributes
            .windows_attributes(tauri_build::WindowsAttributes::new_without_app_manifest());
    }

    tauri_build::try_build(attributes).expect("tauri-build failed");
}

/// Sorted, de-duplicated names of the `#[tauri::command]` functions in the commands module.
fn command_names() -> Vec<String> {
    let mut files = Vec::new();
    if Path::new("src/commands.rs").is_file() {
        files.push(Path::new("src/commands.rs").to_path_buf());
    }
    if let Ok(entries) = fs::read_dir("src/commands") {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "rs") {
                files.push(path);
            }
        }
    }
    let mut names: Vec<String> = files
        .iter()
        .filter_map(|p| fs::read_to_string(p).ok())
        .flat_map(|src| parse_command_names(&src))
        .collect();
    names.sort();
    names.dedup();
    names
}

/// Finds `fn <name>` after each `#[tauri::command]` (or `#[command]`) attribute, skipping any
/// doc comments and other attributes in between.
fn parse_command_names(src: &str) -> Vec<String> {
    let mut names = Vec::new();
    let mut pending = false;
    for line in src.lines() {
        let line = line.trim_start();
        if line.starts_with("#[tauri::command") || line.starts_with("#[command") {
            pending = true;
            continue;
        }
        if !pending || line.is_empty() || line.starts_with("#[") || line.starts_with("//") {
            continue;
        }
        pending = false;
        if let Some(at) = line.find("fn ") {
            let name: String = line[at + 3..]
                .trim_start()
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                names.push(name);
            }
        }
    }
    names
}

fn command_set_toml(names: &[String]) -> String {
    let permissions = names
        .iter()
        .map(|n| format!("\"allow-{}\"", n.replace('_', "-")))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "# Generated by build.rs from the #[tauri::command] functions in src/commands - DO NOT EDIT.\n\
         [[set]]\n\
         identifier = \"app-commands\"\n\
         description = \"Every Crawler AI app command. Granted only to the setup window (capabilities/setup.json).\"\n\
         permissions = [{permissions}]\n"
    )
}

/// Rewriting an unchanged file would retrigger tauri-build's rerun-if-changed on
/// `permissions/` and rebuild on every `cargo` call.
fn write_if_changed(path: &Path, contents: &str) {
    if fs::read_to_string(path).ok().as_deref() == Some(contents) {
        return;
    }
    if let Some(dir) = path.parent() {
        fs::create_dir_all(dir).expect("create permissions/autogenerated");
    }
    fs::write(path, contents).expect("write the app-commands permission set");
}
