import type { CapabilityStatus } from "@/types";

/**
 * A realistic GET /capabilities body covering the four states the UI has to
 * render distinctly: freely on, enabled-but-blocked-by-the-OS (with a fix),
 * blocked-until-installed, and plainly off.
 */
export const CAPS: CapabilityStatus[] = [
  {
    key: "web_browsing",
    label: "Browse the web",
    description: "Fetch and read pages from the public internet.",
    risk: "low",
    enabled: true,
    default_enabled: true,
    available: true,
    availability_reason: "",
    probe_state: "not_required",
    probe_detail: "",
    fix_url: null,
    fix_steps: [],
    effective: "on",
    reason: "",
    can_request_access: false,
    install: null,
    when_denied: "",
    tools: ["web.fetch", "web.search"],
  },
  {
    key: "screen",
    label: "See my screen",
    description:
      "Let the agent take a screenshot of your screen when it needs visual context.",
    risk: "high",
    enabled: true,
    default_enabled: false,
    available: true,
    availability_reason: "",
    probe_state: "denied",
    probe_detail: "Screen Recording permission not granted to /usr/bin/python3.",
    fix_url: "x-apple.systempreferences:com.apple.preference.security?Privacy_ScreenCapture",
    fix_steps: [
      "Open System Settings → Privacy & Security → Screen Recording.",
      "Enable it for /usr/bin/python3 (or your terminal).",
      "Restart the backend.",
    ],
    effective: "blocked",
    reason: "macOS has not granted Screen Recording to /usr/bin/python3.",
    can_request_access: true,
    install: null,
    when_denied: "Screenshot requests are refused until access is granted.",
    tools: ["desktop.screenshot"],
  },
  {
    key: "site_screenshots",
    label: "Take screenshots of websites",
    description:
      "Capture a screenshot of a specific webpage using a hidden headless browser.",
    risk: "medium",
    enabled: true,
    default_enabled: true,
    available: false,
    availability_reason: "The hidden browser is not installed yet.",
    probe_state: "not_required",
    probe_detail: "",
    fix_url: null,
    fix_steps: [],
    effective: "blocked",
    reason: "The hidden browser is not installed yet.",
    can_request_access: false,
    install: "browser",
    when_denied: "Website screenshot requests will fail until the browser is installed.",
    tools: ["web.screenshot"],
  },
  {
    key: "reminders",
    label: "Set reminders",
    description: "Let the agent schedule reminders that notify you later.",
    risk: "low",
    enabled: false,
    default_enabled: true,
    available: true,
    availability_reason: "",
    probe_state: "not_required",
    probe_detail: "",
    fix_url: null,
    fix_steps: [],
    effective: "off",
    reason: "",
    can_request_access: false,
    install: null,
    when_denied: "",
    tools: ["reminders.create", "reminders.list", "reminders.cancel"],
  },
];
