//! Proves the two trust levels end to end, with Tauri's mock runtime and this app's real
//! capabilities (capabilities/setup.json + the ACL build.rs generates): the setup window
//! reaches Tauri's core APIs, the Crawler AI window reaches nothing — not core, not a single
//! app command — whether its page claims the remote origin it really has or a local one.
//!
//! App commands are only ever invoked from the Crawler AI window, where the ACL rejects them
//! before they run, so no command body (and no `docker`) ever executes in these tests.

use tauri::ipc::{CallbackFn, InvokeBody};
use tauri::test::{get_ipc_response, mock_builder, MockRuntime, INVOKE_KEY};
use tauri::webview::InvokeRequest;
use tauri::{App, WebviewUrl, WebviewWindow, WebviewWindowBuilder};

const LOCAL_ORIGIN: &str = "tauri://localhost/index.html";
const CRAWLER_ORIGIN: &str = "http://localhost:3000/";

fn app() -> App<MockRuntime> {
    crawler_ai_desktop::commands::register(mock_builder())
        .build(tauri::generate_context!(test = true))
        .expect("mock app")
}

fn window(app: &App<MockRuntime>, label: &str) -> WebviewWindow<MockRuntime> {
    WebviewWindowBuilder::new(app, label, WebviewUrl::App("index.html".into()))
        .build()
        .expect("mock window")
}

fn invoke(window: &WebviewWindow<MockRuntime>, cmd: &str, origin: &str) -> Result<(), String> {
    get_ipc_response(
        window,
        InvokeRequest {
            cmd: cmd.into(),
            callback: CallbackFn(0),
            error: CallbackFn(1),
            url: origin.parse().unwrap(),
            body: InvokeBody::default(),
            headers: Default::default(),
            invoke_key: INVOKE_KEY.into(),
        },
    )
    .map(|_| ())
    .map_err(|e| e.to_string())
}

/// The app commands, read from the permission set build.rs generated from src/commands.rs.
fn app_commands() -> Vec<String> {
    include_str!("../permissions/autogenerated/app-commands.toml")
        .lines()
        .find(|l| l.starts_with("permissions"))
        .expect("permissions line")
        .split('"')
        .filter_map(|s| s.strip_prefix("allow-"))
        .map(|s| s.replace('-', "_"))
        .collect()
}

#[test]
fn setup_window_reaches_core_apis() {
    let app = app();
    let setup = window(&app, crawler_ai_desktop::windows::SETUP_WINDOW);
    assert_eq!(invoke(&setup, "plugin:app|version", LOCAL_ORIGIN), Ok(()));
}

#[test]
fn crawler_window_reaches_nothing() {
    let app = app();
    let crawler = window(&app, crawler_ai_desktop::windows::CRAWLER_WINDOW);
    let commands = app_commands();
    assert!(!commands.is_empty(), "build.rs found no app commands");

    for origin in [CRAWLER_ORIGIN, LOCAL_ORIGIN] {
        let err = invoke(&crawler, "plugin:app|version", origin).expect_err(origin);
        assert!(err.contains("not allowed"), "core from {origin}: {err}");
        for cmd in &commands {
            let err = invoke(&crawler, cmd, origin).expect_err(cmd);
            assert!(err.contains("not allowed"), "{cmd} from {origin}: {err}");
        }
    }
}
